drop extension if exists "pg_net";


  create table "public"."feedin_logs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "date" date not null,
    "time" time without time zone not null default now(),
    "amount" bigint not null,
    "comment" character varying
      );


alter table "public"."feedin_logs" enable row level security;

CREATE UNIQUE INDEX feedin_logs_pkey ON public.feedin_logs USING btree (id);

alter table "public"."feedin_logs" add constraint "feedin_logs_pkey" PRIMARY KEY using index "feedin_logs_pkey";

grant delete on table "public"."feedin_logs" to "anon";

grant insert on table "public"."feedin_logs" to "anon";

grant references on table "public"."feedin_logs" to "anon";

grant select on table "public"."feedin_logs" to "anon";

grant trigger on table "public"."feedin_logs" to "anon";

grant truncate on table "public"."feedin_logs" to "anon";

grant update on table "public"."feedin_logs" to "anon";

grant delete on table "public"."feedin_logs" to "authenticated";

grant insert on table "public"."feedin_logs" to "authenticated";

grant references on table "public"."feedin_logs" to "authenticated";

grant select on table "public"."feedin_logs" to "authenticated";

grant trigger on table "public"."feedin_logs" to "authenticated";

grant truncate on table "public"."feedin_logs" to "authenticated";

grant update on table "public"."feedin_logs" to "authenticated";

grant delete on table "public"."feedin_logs" to "service_role";

grant insert on table "public"."feedin_logs" to "service_role";

grant references on table "public"."feedin_logs" to "service_role";

grant select on table "public"."feedin_logs" to "service_role";

grant trigger on table "public"."feedin_logs" to "service_role";

grant truncate on table "public"."feedin_logs" to "service_role";

grant update on table "public"."feedin_logs" to "service_role";


